# Generated by Django 5.2.17 on 2026-09-30 14:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='match',
            field=models.JSONField(default=core.models.initial_match),
        ),
    ]
