# Generated by Django 5.2.17 on 2026-09-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invoice_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('entityType', models.CharField(db_index=True, max_length=32)),
                ('entityId', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='protected-documents/')),
                ('sizeKb', models.PositiveIntegerField()),
                ('uploadedOn', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=20)),
                ('checksum', models.CharField(max_length=64)),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
