# Generated by Django 5.2.17 on 2026-10-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='documents',
            field=models.JSONField(default=list),
        ),
    ]
